kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
# below options are needed as default efs config expects iam auth and tls comms
mountOptions:
  - tls
  - iam
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0a97bc75c3e09ffd2
  directoryPerms: "700"
