---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f4ac51547e269599
  mountOptions:
    - tls
    - iam

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: efs-ubuntu
spec:
  selector:
    matchLabels:
      app: efs-ubuntu
  replicas: 2
  template:
    metadata:
      labels:
        app: efs-ubuntu
    spec:
      containers:
        - name: efs-ubuntu
          image: ubuntu
          command:
            - sleep
            - infinity
          volumeMounts:
            - name: persistent-data
              mountPath: /data
      volumes:
        - name: persistent-data
          persistentVolumeClaim:
            claimName: efs

