---
- name: Install Ansible
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - ansible       # duh
    - boto3         # needed by amazon.aws.*
    - passlib       # needed by community.general.htpasswd
