- name: Setup state
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/cloud_config.yml
  tasks:
    - name: Check if cloud provider is defined
      ansible.builtin.fail:
        msg: Cloud provider must be specified ("cloud_provider" variable is not set)
      when: cloud_provider is undefined
    - name: Check if etude name is defined
      ansible.builtin.fail:
        msg: Etude name must be specified ("etude" variable is not set)
      when: etude is undefined
    - name: Set state resource name
      ansible.builtin.set_fact:
        state_resource: "{{ state_resource_prefix }}-{{ etude }}"
    - name: Create state store configuration on AWS
      block:
        - name: create s3 bucket for terraform state
          amazon.aws.s3_bucket:
            name: "{{ state_resource }}"
            state: present
            region: "{{ cloud_providers[cloud_provider].region }}"
        - name: create dynamodb table and key for state locking
          community.aws.dynamodb_table:
            name: "{{ state_resource }}"
            region: "{{ cloud_providers[cloud_provider].region }}"
            hash_key_name: LockID
            hash_key_type: STRING
            billing_mode: PAY_PER_REQUEST
      when: cloud_provider == "aws"

